.TH XFILE 1
.SH NAME
xfile \- graphical file manager\.
.SH SYNOPSIS
xfile [OPTIONS] [DIRECTORY]
.PP
xfile-open FILENAME\.\.\.
.SH DESCRIPTION
.PP
XFile is a file manager for Unix systems running X11\.
.SS Options
.TP
\fB+/-a\fP
Ignore/show entries starting with a dot character. 
.TP
\fB-f\fP <glob pattern>
Hide files matching glob pattern specified\. Prefix the pattern with the
negation ! character to hide matching files\.
.TP
\fb-l\fP
Invert sort direction (see sortDirection resource)\.
.TP
\fB-s\fP(n|s|t|f|x)
Specify sort order: \fBn\fPame, \fBs\fPize, \fBt\fPime, \fBf\fPile type, suffi\fBx\fP\.
.SS Arguments
XFile will display current working directory if invoked without arguments\.
.PP
If invoked as xfile-open (through a symbolic link), XFile will match each file
name specified against the file type database, run the default action if
defined, and finally quit\. 
 
