# XFile Linux Makefile

PREFIX = /usr
MANDIR = $(PREFIX)/share/man
SHAREDIR = $(PREFIX)/share/xfile
APPLRESDIR = /etc/X11/app-defaults

INCDIRS = -I/usr/local/include 
LIBDIRS = -L/usr/local/lib

CFLAGS = -O2 -Wall

include common.mf

# Set to APPDEFS_CORE for core fonts
APPDEFS = $(APPDEFS_XFT)

install: common_install

-include .depend
