# XFile Darwin Makefile

PREFIX = /usr/local
MANDIR = $(PREFIX)/share/man
SHAREDIR = $(PREFIX)/share/xfile
APPLRESDIR = $(PREFIX)/etc/X11/app-defaults

INCDIRS = -I$(HOMEBREW_PREFIX)/include 
LIBDIRS = -L$(HOMEBREW_PREFIX)/lib

CFLAGS = -O2 -Wall

include common.mf

# May be set to APPDEFS_CORE for core fonts
APPDEFS = $(APPDEFS_XFT)

install: common_install

-include .depend
