#!/bin/sh

INFILES=$(grep -l '\.xbm' *.xbm)

for n in $INFILES; do
	echo "$n"
	if [ -f $n.bak ]; then rm $n.bak; fi
	mv $n $n.bak
	sed 's/.xbm//g' $n.bak > $n
done

if [ -n "$INFILES" ]; then rm *.bak; fi
